et_astlf_controller_node:
  ros__parameters:
    wheelbase: 0.32
    target_speed: 0.5
    max_steer_angle: 0.45
    control_rate: 50.0

    c1: 0.3
    c2: 1.0
    eps: -0.42
    sigma: 0.4
    gamma: 0.2
    c_gain: 0.18
    mu1: 0.02
    mu0: 0.02
    beta1_min: 4.0
    beta1_init: 4.48

    use_event_trigger: false
    lookahead_distance: 0.6
    goal_tolerance: 0.20
    publish_debug: true
    save_error_plot_on_shutdown: true
    plot_output_dir: /root/astlf_plots
    plot_window_s: 600.0
    plot_save_period_s: 1.0
    cmd_output_type: twist

u_path_publisher_node:
  ros__parameters:
    frame_id: odom
    straight_length: 2.0
    track_width: 1.0
    point_spacing: 0.10
    publish_rate: 2.0
    regenerate_on_start: true

error_plotter_node:
  ros__parameters:
    plot_output_dir: /root/astlf_plots
    plot_window_s: 600.0
    plot_save_period_s: 1.0
