et_astlf_controller_node:
  ros__parameters:
    wheelbase: 0.32
    target_speed: 0.5
    max_steer_angle: 0.45
    control_rate: 50.0

    c1: 0.3
    c2: 1.0
    eps: -0.42
    sigma: 0.4
    gamma: 0.2
    c_gain: 0.18
    mu1: 0.02
    mu0: 0.02
    beta1_min: 4.0
    beta1_init: 4.48

    use_event_trigger: false
    lookahead_distance: 0.6
